// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE80NJ32x9Kywvg-OZ92aY7G2vkk-jRPo',
    appId: '1:286359690783:android:752f30182c76fa315abf2a',
    messagingSenderId: '286359690783',
    projectId: 'learn-e-639fc',
    storageBucket: 'learn-e-639fc.firebasestorage.app',
    databaseURL: 'https://learn-e-639fc-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK0U0oEo3fqae2PzgOhADbsRPp7XrGaME',
    appId: '1:286359690783:web:0474fbafae5a21c95abf2a',
    messagingSenderId: '286359690783',
    projectId: 'learn-e-639fc',
    authDomain: 'learn-e-639fc.firebaseapp.com',
    storageBucket: 'learn-e-639fc.firebasestorage.app',
    databaseURL: 'https://learn-e-639fc-default-rtdb.asia-southeast1.firebasedatabase.app/'
  );

}